version: "3"
services:
  # 配置个代理nginx，做一层密码登录
  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    environment:
      TZ: "Asia/Shanghai"
      LANG: C.UTF-8
    privileged: true
    ports:
      - "3001:3001" # prometheus
      - "3002:3002" # grafana
      - "3003:3003" # alertmanager
      - "3004:3004" # pushgateawy
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./data/nginx:/app:rw
      - ./conf/nginx/conf.d/vhost:/etc/nginx/conf.d/vhost:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/nginx:rw
      - ./conf/nginx/htpasswd:/etc/nginx/htpasswd:rw
    restart: always
    networks:
      prom:
        ipv4_address: ${NGINX_IPV4}

  prometheus:
    image: prom/prometheus:${PROME_VERSION}
    privileged: true
    volumes:
      - ${PROME_YML}:/etc/prometheus/prometheus.yml
      - ${PROME_RULES_YML}:/etc/prometheus/rules.yml
      - ${PROME_DATA_DIR}:/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle"
    restart: "always"
    ports:
      - ${PROME_PORT}:9090
    networks:
      prom:
        ipv4_address: ${PROM_IPV4}


  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    privileged: true
    ports:
      - "${GRAFANA_PORT}:3000"
    restart: "always"
    volumes:
      - ./conf/grafana/grafana.ini:/etc/grafana/grafana.ini:rw
      - ${GRAFANA_DATA_DIR}:/var/lib/grafana:rw
      - /etc/localtime:/etc/localtime
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_INIT_PASSWD}
    networks:
      prom:
        ipv4_address: ${GRAFANA_IPV4}


  alertmanager:
    image: prom/alertmanager:${ALERTMANAGER_VERSION}
    privileged: true
    restart: "always"
    volumes:
      - ${ALERTMANAGER_YML}:/etc/alertmanager/alertmanager.yml
    ports:
      - "${ALERTMANAGER_PORT}:9093"
    networks:
      prom:
        ipv4_address: ${ALERTMANAGER_IPV4}


  pushgateway:
    image: prom/pushgateway:${PUSHGATEWAY_VERSION}
    privileged: true
    restart: "always"
    ports:
      - "${PUSHGATEWAY_PORT}:9091"
    networks:
      prom:
        ipv4_address: ${PUSHGATEWAY_IPV4}


  node-exporter:
    image: prom/node-exporter:${NODE_EXTPORT_VERSION}
    privileged: true
    restart: "always"
    ports:
      - "${NODE_EXTPORT_PORT}:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      prom:
        ipv4_address: ${NODE_EXPORT_IPV4}

# 启动mysql export
# docker run -d --restart=always --name mysqld-exporter -p 9104:9104   -e DATA_SOURCE_NAME="root:123456@(192.168.33.10:3306)/"   prom/mysqld-exporter

#启动redis export
# docker run -d --restart=always --name redis_exporter -p 9121:9121 oliver006/redis_exporter --redis.addr=redis://192.168.33.10:6379

#启动nginx export
#docker run --restart=always -d -p 9113:9113 nginx/nginx-prometheus-exporter:0.8.0 -nginx.scrape-uri http://192.168.33.10/stub_status


networks:
  prom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_MASK}

